<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_news_slider"
 *
 * Auto generated by Extension Builder 2018-09-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => '[NITSAN]  News Slider',
    'description' => 'This extension allow you to create beautiful news slider for your website. This extension has come up with number of popular JQuery slider plugins like Nivo Slider, Owlcarousel Slider, Royal Slider, Slidejs Slider, Slick Slider.
News slider for easy and handy use!',
    'category' => 'plugin',
    'author' => 'Sanjay Chauhan',
    'author_email' => 'sanjay@nitsan.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-9.5.99',
            'news' => '3.0.0-7.9.9',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
