services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsNewsSlider\:
    resource: '../Classes/*'

  NITSAN\NsNewsSlider\Event\Setup:
    tags:
      - name: event.listener
        identifier: 'ns-news-slider'
        method: 'executeOnSignal'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
  
  NITSAN\NsNewsSlider\Event\BackendUserLogin:
    tags:
      - name: event.listener
        identifier: 'ns-news-slider-backend-login'
        method: 'dispatch'
        event: TYPO3\CMS\Core\Authentication\Event\AfterUserLoggedInEvent